//
//

#ifndef __CONSTANTS_H
#define __CONSTANTS_H

// CRSF CONSTANTS
#define CRSF_MIN 172
#define CRSF_MAX 1811
#define CRSF_MID (CRSF_MIN + (CRSF_MAX - CRSF_MIN) / 2)
#define CRSF_ONE_THIRD (CRSF_MIN + (CRSF_MAX - CRSF_MIN) / 3)
#define CRSF_TWO_THIRD (CRSF_MIN + 2 * (CRSF_MAX - CRSF_MIN) / 3)

// PWM CONSTANTS
#define PWM_MIN 500
#define PWM_MAX 1250
#define PWM_MID (PWM_MIN + (PWM_MAX - PWM_MIN) / 2)
#define PWM_DISARMED 500

#define PWM_CHANNEL_COUNT 5
#define PWM_UPDATE_PERIOD_MS 10

// NORMALISED CHANNEL CONSTANTS
#define NORM_RANGE 1000

// CHANNEL MAPPING
#define CHANNEL_LON_CYC 0
#define CHANNEL_LAT_CYC 1
#define CHANNEL_COLLECTIVE 2
#define CHANNEL_PEDALS 3
#define CHANNEL_THROTTLE 4
#define CHANNEL_ARM 5
#define CHANNEL_PREARM 6
#define CHANNEL_FLIGHT_MODE 7
#define CHANNEL_PIT_MODE 8

// ACTUATOR MAPPING
#define MIXER_INPUT_CHANNEL_COUNT 5
#define ACTUATOR_CHANNEL_COUNT 5

#define ACTUATOR_SWASH_LEFT 0
#define ACTUATOR_SWASH_RIGHT 1
#define ACTUATOR_SWASH_AFT 2
#define ACTUATOR_MAIN_ROTOR 3
#define ACTUATOR_TAIL_ROTOR 4

#define ACTUATOR_SWASH_LP_PARAM 4
#define ACTUATOR_MAIN_LP_PARAM 16
#define ACTUATOR_MAIN_MAX_DELTA 2
#define ACTUATOR_TAIL_LP_PARAM 4


// HELI SETTINGS
#define ROTOR_PHASE_ANGLE_SIN ? // calculated from φ=90deg
#define ROTOR_PHASE_ANGLE_COS ? // calculated from φ=90deg
#define ROTOR_LON_TRIM 0
#define ROTOR_LAT_TRIM 0
#define ROTOR_PEDAL_TRIM 0
#define ROTOR_MAIN_TO_PEDAL_INV_GAIN 2 // => 1/G

// RADIO SETTINGS
#define MAX_RADIO_STATS_AGE 500 // ms
#define MIN_LINK_QLY 50 // %

// OTHER SETTINGS
#define BLINK_TIME 50 // ms


#endif /* __CONSTANTS_H */
